services:
  postgres:
    container_name: PetFinder.Postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "pet_finder"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  seq:
    container_name: PetFinder.Seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 5340:80


volumes:
  postgres-data: